adminpanel/urls.py
from django.contrib.auth.decorators import user_passes_test
from django.urls import path
from django.contrib.auth.views import LoginView
from .views import (AdminPanelView, AddProductView, AddPromoCodeView, OrdersView, StockView, OpinionsView,
                    set_off_product, ProductEditView, mark_order_as_shipped, mark_order_as_delivered, delete_opinion,
                    CardDetailsView,add_perfume_options,set_on_product,Utilities,edit_shipping_price,edit_shipping_free,edit_photo,delete_coupon,DiscoversetMainPage,
                    EditDiscoverSet,add_discoverset_options,add_perfume_to_category,remove_perfume_from_category)


def staff_member_required(user):
    return user.is_authenticated and user.is_staff

urlpatterns = [
    path('login/', LoginView.as_view(), name='adminlogin'),
    path('', user_passes_test(staff_member_required, login_url='/login/')(AdminPanelView.as_view()), name='adminpanel'),
    path('addproduct/', user_passes_test(staff_member_required, login_url='/login/')(AddProductView.as_view()), name='addproduct'),
    path('addpromocode/', user_passes_test(staff_member_required, login_url='/login/')(AddPromoCodeView.as_view()), name='addpromocode'),
    path('orders/', user_passes_test(staff_member_required, login_url='/login/')(OrdersView.as_view()), name='orders'),
    path('stock/', user_passes_test(staff_member_required, login_url='/login/')(StockView.as_view()), name='stock'),
    path('opinions/', user_passes_test(staff_member_required, login_url='/login/')(OpinionsView.as_view()), name='opinions'),
    path('setoff_product/<int:product_id>/', user_passes_test(staff_member_required, login_url='/login/')(set_off_product), name='setoff_product'),
    path('seton_product/<int:product_id>/', user_passes_test(staff_member_required, login_url='/login/')(set_on_product), name='seton_product'),
    path('edit_product/<int:product_id>/', user_passes_test(staff_member_required, login_url='/login/')(ProductEditView.as_view()), name='edit_product'),
    path('mark_order_as_shipped/<int:order_id>/', user_passes_test(staff_member_required, login_url='/login/')(mark_order_as_shipped), name='mark_order_as_shipped'),
    path('mark_order_as_delivered/<int:order_id>/', user_passes_test(staff_member_required, login_url='/login/')(mark_order_as_delivered), name='mark_order_as_delivered'),
    path('delete_opinion/<int:opinion_id>/', user_passes_test(staff_member_required, login_url='/login/')(delete_opinion), name='delete_opinion'),
    path('order_detail/<int:card_id>/', user_passes_test(staff_member_required, login_url='/login/')(CardDetailsView.as_view()), name='order_detail'),
    path('addperfumeoptions/<int:product_id>/', user_passes_test(staff_member_required, login_url='/login/')(add_perfume_options), name='addperfumeoptions'),
    path('utilities/', user_passes_test(staff_member_required, login_url='/login/')(Utilities.as_view()), name='utilities'),
    path('edit_shipping_price/', user_passes_test(staff_member_required, login_url='/login/')(edit_shipping_price), name='edit_shipping_price'),
    path('edit_shipping_free/', user_passes_test(staff_member_required, login_url='/login/')(edit_shipping_free), name='edit_shipping_free'),
    path('edit_photo/<str:name>/', user_passes_test(staff_member_required, login_url='/login/')(edit_photo), name='edit_photo'),
    path('delete_coupon/<int:coupon_id>/', user_passes_test(staff_member_required, login_url='/login/')(delete_coupon), name='delete_coupon'),
    path('discover_sets/',user_passes_test(staff_member_required,login_url='/login/')(DiscoversetMainPage.as_view()), name="discover_sets"),
    path('editdiscover_sets/<int:product_id>/',user_passes_test(staff_member_required,login_url='/login/')(EditDiscoverSet.as_view()),name="editdiscover_set"),
    path('add_discoverset_options/<int:product_id>/',user_passes_test(staff_member_required,login_url="/login/")(add_discoverset_options),name="adddiscoversetoptions"),
    path('add_product_to_category/<int:product_id>/<int:category_id>/',user_passes_test(staff_member_required,login_url="/login/")(add_perfume_to_category),name="add_product_to_category"),
    path('remove_product_from_category/<int:product_id>/<int:category_id>/',user_passes_test(staff_member_required,login_url="/login/")(remove_perfume_from_category),name="remove_product_from_category")
]

sklep/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('users.urls')),
    path('',include('product.urls')),
    path('adminpanel/',include('adminpanel.urls')),
    path('utilities/',include('utilities.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

adminpanel/models.py
from django.db import models

# Create your models here.

product/models.py
import django
from django.db import models
from users.models import User
from utilities.models import ConstValue, ConstFile
import datetime


class Product(models.Model):
    title = models.CharField(max_length=50)
    price = models.IntegerField()
    image = models.ImageField(upload_to="images/")
    image2 = models.ImageField(upload_to="images/", blank=True,null=True)
    description = models.TextField()
    is_featured = models.BooleanField(default=False)
    amount = models.IntegerField(default=1)
    is_on = models.BooleanField(default=True, blank=True)
    stars = models.IntegerField(default=0)
    is_discoverset = models.BooleanField(default=False)
    is_perfume = models.BooleanField(default=False)

    def __str__(self):
        return self.title

    @staticmethod
    def set_off(self):
        self.is_on = False
        self.save()

    @staticmethod
    def set_on(self):
        self.is_on = True
        self.save()

    @classmethod
    def sell(cls):
        if cls.amount == 1:
            cls.set_off()

    @staticmethod
    def make_discoverset(self):
        self.is_discoverset = True
        self.save()

    @staticmethod
    def make_perfume(self):
        self.is_perfume = True
        self.save()


class PerfumeOptions(models.Model):
    amount = models.IntegerField(default=1)  # in mililitres
    price = models.IntegerField(default=0)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='perfume_options', null=True,
                                blank=True)
    title = models.CharField(max_length=50, default="")

    def __str__(self):
        return f"{self.amount} ml - {self.price} zł - {self.title}"


class Opinion(models.Model):
    author = models.ForeignKey(to=User, on_delete=models.CASCADE, default="")
    description = models.TextField(default="")
    rated = models.IntegerField(default=0)
    product = models.ForeignKey(to=Product, on_delete=models.CASCADE, default="")


class Discounts(models.Model):
    discount = models.IntegerField(default=0)


class CardItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, default="", blank=True)
    quantity = models.IntegerField(default=1, blank=True)
    price = models.IntegerField(default=0, blank=True)
    card = models.ForeignKey(to='Card', on_delete=models.CASCADE, default="", blank=True)
    size = models.ManyToManyField(to=PerfumeOptions, default="", blank=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return f"{self.product.title} - {self.quantity} szt. - {self.price} zł"


class Card(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.CASCADE, default="", blank=True)
    quantity = models.IntegerField(default=1, blank=True)
    price = models.IntegerField(default=0)
    street = models.CharField(max_length=100, default="", blank=True)
    city = models.CharField(max_length=100, default="", blank=True)
    postal_code = models.CharField(max_length=6, default="", blank=True)
    phone_number = models.CharField(max_length=9, default="", blank=True)
    email = models.EmailField(default="", blank=True)
    first_name = models.CharField(max_length=50, default="", blank=True)
    last_name = models.CharField(max_length=50, default="", blank=True)
    promo_code = models.CharField(max_length=10, default="", blank=True)
    is_order = models.BooleanField(default=False, blank=True)
    date = models.DateTimeField(default=django.utils.timezone.now, blank=True)
    is_shipped = models.BooleanField(default=False)
    is_delivered = models.BooleanField(default=False)
    is_paczkomat = models.BooleanField(default=False)
    free_shipping = models.BooleanField(default=False)
    paczkomat = models.CharField(max_length=50, default="", blank=True)

    def __str__(self):
        return f"Zamowienie nr {self.id} - {self.user.last_name} "

    def get_total_price(self, products):
        self.price = 0
        for product in products:
            self.price += product.price
        return self.price

    def make_order(self):
        self.is_order = True
        self.save()

    @staticmethod
    def calculate_shipping(self):
        if self.price >= int(ConstValue.objects.get(name="free_shipping").value):
            self.free_shipping = True
            self.save()
        else:
            self.free_shipping = False
            self.save()


class Promo_code(models.Model):
    code = models.CharField(max_length=10, default="")
    discount = models.IntegerField(default=0)
    title = models.CharField(max_length=50, default="")
    max_count = models.IntegerField(default=0)

    def __str__(self):
        return f"{self.title} - {self.code} - {self.discount}%"

    def check_using_limit(self):
        if self.max_count > 0:
            self.max_count -= 1
            self.save()
            return True
        else:
            return False


class Category(models.Model):
    title = models.CharField(max_length=50, default="")
    products = models.ManyToManyField(to=Product, default="", blank=True)

    def __str__(self):
        return self.title

adminpanel/forms.py
from typing import Any

from django.contrib.auth import authenticate
from django.forms import forms, ModelForm
from users.models import User
from product.models import Product, Promo_code, PerfumeOptions


class Loginform(forms.Form):
    class Meta:
        model = User
        fields = ["email", "password"]

    def check_credentials(self, email, password) -> Any | None:
        user = authenticate(email=email, password=password)
        if user is not None:
            return user
        else:
            return None


class AddProductForm(ModelForm):
    class Meta:
        model = Product
        fields = "__all__"


class AddpromoCodeForm(ModelForm):
    class Meta:
        model = Promo_code
        fields = "__all__"


class PerfumeOptionsForm(ModelForm):
    class Meta:
        model = PerfumeOptions
        fields = ['amount', 'price']


class DiscoversetForm(ModelForm):
    class Meta:
        model = Product
        fields = "__all__"

templates/adminpanel/addproduct.html
{% extends 'base_admin.html' %}

{% block content %}
<div class="container mt-4">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                    <h1 class="display-4 text-center">Dodaj produkt</h1>
                </div>
                <div class="card-body">
                    <form method="post" action="{% url 'addproduct' %}" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="id_title">Tytuł:</label>
                            <input type="text" class="form-control" id="id_title" name="title">
                        </div>
                        <div class="form-group">
                            <label for="id_price">Cena:</label>
                            <input type="number" class="form-control" id="id_price" name="price" step="0.01">
                        </div>
                        <div class="form-group">
                            <label for="id_image">Zdjęcie 1:</label>
                            <input type="file" class="form-control-file" id="id_image" name="image">
                        </div>
                        <div class="form-group">
                            <label for="id_image2">Zdjęcie 2:</label>
                            <input type="file" class="form-control-file" id="id_image2" name="image2" accept="image/*">
                        </div>
                        <div class="form-group">
                            <label for="id_description">Opis:</label>
                            <textarea class="form-control" id="id_description" name="description" rows="3"></textarea>
                        </div>
                        <div class="form-check">
                            <input type="checkbox" class="form-check-input" id="id_is_featured" name="is_featured">
                            <label class="form-check-label" for="id_is_featured">Czy jest wyróżniony?</label>
                        </div>
                        <div class="form-group">
                            <label for="id_amount">Ilość:</label>
                            <input type="number" class="form-control" id="id_amount" name="amount" value="1">
                        </div>
                        <div class="form-check">
                            <input type="checkbox" class="form-check-input" id="id_is_on" name="is_on" checked>
                            <label class="form-check-label" for="id_is_on">Czy jest aktywny?</label>
                        </div>
                        <div class="form-group">
                            <label for="id_stars">Liczba gwiazdek:</label>
                            <input type="number" class="form-control" id="id_stars" name="stars" value="0">
                        </div>
                        <div class="form-check">
                            <input type="checkbox" class="form-check-input" id="id_is_discoverset" name="is_discoverset">
                            <label class="form-check-label" for="id_is_discoverset">Discover set</label>
                        </div>
                        <div class="form-check">
                            <input type="checkbox" class="form-check-input" id="id_is_perfume" name="is_perfume">
                            <label class="form-check-label" for="id_is_perfume">Perfuma</label>
                        </div>
                        <button type="submit" class="btn btn-primary">Zapisz</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/adminpanel/addpromocode.html
{% extends 'base_admin.html' %}

{% block content %}
<div class="container mt-4">
    <div class="card" style="background-color: #f8f9fa; margin-bottom: 20px;">
        <div class="card-body">
            <h1 class="card-title">Dodaj promo code</h1>
            <div class="row">
                <div class="col-md-6">
                    <form method="post" action="{% url 'addpromocode' %}" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary">Zapisz</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/adminpanel/discoversets.html
{% extends 'base_admin.html' %}

{% block content %}
<div class="container mt-4">
    <h1 class="mb-4">Discover sety</h1>
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">

                <div class="card-body">
                    <form method="post" action="{% url 'discover_sets' %}" enctype="multipart/form-data" class="row g-3">
                        {% csrf_token %}
                        {{ form.non_field_errors }}
                        <div class="col-12">
                            <label for="inputTitle" class="form-label">Tytuł</label>
                            {{ form.title }}
                            {{ form.title.errors }}
                        </div>
                        <div class="col-12">
                            <label for="inputPrice" class="form-label">Cena</label>
                            {{ form.price }}
                            {{ form.price.errors }}
                        </div>
                        <div class="col-12">
                            <label for="inputDescription" class="form-label">Opis</label>
                            {{ form.description }}
                            {{ form.description.errors }}
                        </div>
                        <div class="col-12">
                            <label for="inputImage" class="form-label">Obraz</label>
                            {{ form.image }}
                            {{ form.image.errors }}
                        </div>

                        <div class="col-12">
                            <label for="inputAmount" class="form-label">Ilość</label>
                            {{ form.amount }}
                            {{ form.amount.errors }}
                        </div>
                        <div class="col-12">
                            <label for="inputIsOn" class="form-label">Czy jest włączony</label>
                            {{ form.is_on }}
                            {{ form.is_on.errors }}
                        </div>
                        <div class="col-12">
                            <label for="inputStars" class="form-label">Gwiazdki</label>
                            {{ form.stars }}
                            {{ form.stars.errors }}
                        </div>
                        <div class="col-12">
                            <button type="submit" class="btn btn-primary">Zapisz zmiany</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="row">

                 <div class="card" style="margin-bottom: 20px;">
                <div class="card-body">
                    <h5 class="card-title mb-4">Lista discover setow</h5>
                    <div class="row">
    {% for product in discover_sets %}
        <div class="col-md-3 mb-4">
            <div class="card">
                <img src="{{ product.image.url }}" class="card-img-top" alt="{{ product.title }}">
                <div class="card-body">
                    <h5 class="card-title"><a href="{% url 'editdiscover_set' product.id %}">{{ product.title }}</a></h5>
                    <p class="card-text">{{ product.description }}</p>
                    <p class="card-text">Ilosc: {{ product.amount }}</p>
                    <p class="card-text">Cena: {{ product.price }}</p>
                </div>
            </div>
        </div>
    {% endfor %}
</div>


                </div>
            </div>
            </div>
           <div class="row">

</div>


        </div>
    </div>
</div>
{% endblock %}

templates/adminpanel/editdiscoverset.html
{% extends 'base_admin.html' %}

{% block content %}
<div class="container mt-4">
    <h1 class="mb-4">Edytuj produkt</h1>
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-body">
                    <form method="post" action="{% url 'editdiscover_set' product.id %}" enctype="multipart/form-data" class="row g-3">
                        {% csrf_token %}
                        {{ form.non_field_errors }}
                        <div class="col-12">
                            <label for="inputTitle" class="form-label">Tytuł</label>
                            {{ form.title }}
                            {{ form.title.errors }}
                        </div>
                        <div class="col-12">
                            <label for="inputPrice" class="form-label">Cena</label>
                            {{ form.price }}
                            {{ form.price.errors }}
                        </div>
                        <div class="col-12">
                            <label for="inputDescription" class="form-label">Opis</label>
                            {{ form.description }}
                            {{ form.description.errors }}
                        </div>
                        <div class="col-12">
                            <label for="inputImage" class="form-label">Obraz</label>
                            {{ form.image }}
                            {{ form.image.errors }}
                        </div>
                        <div class="col-12">
                            <label for="inputIsFeatured" class="form-label">Czy wyróżniony</label>
                            {{ form.is_featured }}
                            {{ form.is_featured.errors }}
                        </div>
                        <div class="col-12">
                            <label for="inputAmount" class="form-label">Ilość</label>
                            {{ form.amount }}
                            {{ form.amount.errors }}
                        </div>
                        <div class="col-12">
                            <label for="inputIsOn" class="form-label">Czy jest włączony</label>
                            {{ form.is_on }}
                            {{ form.is_on.errors }}
                        </div>
                        <div class="col-12">
                            <label for="inputStars" class="form-label">Gwiazdki</label>
                            {{ form.stars }}
                            {{ form.stars.errors }}
                        </div>
                        <div class="col-12">
                            <button type="submit" class="btn btn-primary">Zapisz zmiany</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="row">

                 <div class="card" style="margin-bottom: 20px;">
                <div class="card-body">
                    <h5 class="card-title mb-4">Ustawienia discoverset</h5>
                    <form method="post" action="{% url 'adddiscoversetoptions' product.id %}">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="id_amount" class="form-label">Ilość dni?</label>
                            {{ perfume_form.amount }}
                        </div>
                        <div class="mb-3">
                            <label for="id_price" class="form-label">Cena</label>
                            <div class="input-group">
                                <span class="input-group-text">PLN</span>
                                {{ perfume_form.price }}
                            </div>
                        </div>

                        <button type="submit" class="btn btn-primary">Dodaj opcję</button>
                    </form>
                </div>
            </div>
            </div>
           <div class="row">
    <div class="card">
        <div class="card-body">
            <h5 class="card-title">Opcje Perfum</h5>
            <div class="row">
                {% for option in product_options %}
                <div class="col-md-4 mb-3">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">{{ option.product.title }}</h6>
                            <p class="card-text">Ilość: {{ option.amount }} </p>
                            <p class="card-text">Cena: {{ option.price }} PLN</p>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>


        </div>
    </div>
</div>
{% endblock %}

templates/adminpanel/editproduct.html
{% extends 'base_admin.html' %}

{% block content %}
<div class="container mt-4">
    <h1 class="mb-4">Edytuj produkt</h1>
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-body">
                    <form method="post" action="{% url 'edit_product' product.id %}" enctype="multipart/form-data" class="row g-3">
                        {% csrf_token %}
                        {{ form.non_field_errors }}
                        <div class="col-12">
                            <label for="inputTitle" class="form-label">Tytuł</label>
                            {{ form.title }}
                            {{ form.title.errors }}
                        </div>
                        <div class="col-12">
                            <label for="inputPrice" class="form-label">Cena</label>
                            {{ form.price }}
                            {{ form.price.errors }}
                        </div>
                        <div class="col-12">
                            <label for="inputDescription" class="form-label">Opis</label>
                            {{ form.description }}
                            {{ form.description.errors }}
                        </div>
                        <div class="col-12">
                            <label for="inputImage" class="form-label">Obraz</label>
                            {{ form.image }}
                            {{ form.image.errors }}
                        </div>
                        <div class="col-12">
                            <label for="inputIsFeatured" class="form-label">Czy wyróżniony</label>
                            {{ form.is_featured }}
                            {{ form.is_featured.errors }}
                        </div>
                        <div class="col-12">
                            <label for="inputAmount" class="form-label">Ilość</label>
                            {{ form.amount }}
                            {{ form.amount.errors }}
                        </div>
                        <div class="col-12">
                            <label for="inputIsOn" class="form-label">Czy jest włączony</label>
                            {{ form.is_on }}
                            {{ form.is_on.errors }}
                        </div>
                        <div class="col-12">
                            <label for="inputStars" class="form-label">Gwiazdki</label>
                            {{ form.stars }}
                            {{ form.stars.errors }}
                        </div>
                        <div class="col-12">
                            <button type="submit" class="btn btn-primary">Zapisz zmiany</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="row">

                 <div class="card" style="margin-bottom: 20px;">
                <div class="card-body">
                    <h5 class="card-title mb-4">Ustawienia perfum</h5>
                    <form method="post" action="{% url 'addperfumeoptions' product.id %}">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="id_amount" class="form-label">Ilość (ml)</label>
                            {{ perfume_form.amount }}
                        </div>
                        <div class="mb-3">
                            <label for="id_price" class="form-label">Cena</label>
                            <div class="input-group">
                                <span class="input-group-text">PLN</span>
                                {{ perfume_form.price }}
                            </div>
                        </div>
                      
                        <button type="submit" class="btn btn-primary">Dodaj opcję</button>
                    </form>
                </div>
            </div>
            </div>
            <div class="row">
          <div class="card"  style="margin-bottom: 20px;">
        <div class="card-body">
            <h5 class="card-title">Opcje Perfum</h5>
            <div class="row">
                {% for option in perfume_options %}
                <div class="col-md-4 mb-3">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">{{ option.product.title }}</h6>
                            <p class="card-text">Ilość: {{ option.amount }} ml</p>
                            <p class="card-text">Cena: {{ option.price }} PLN</p>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
            <div class="row">
                <div class="card">
        <div class="card-body">
            <h5 class="card-title">Kategorie</h5>
           <div class="row">
    {% for category in categories %}
    <div class="col-md-4 mb-3">
        {% if product in category.products.all %}
        <div class="card" style="background-color: #a41515;">
            <div class="card-body">
                <a href="{% url 'remove_product_from_category' product.id category.id %}"><h6 class="card-title">{{ category.title }}</h6></a>
                <!-- Dodaj tutaj dodatkowe informacje na temat produktu, jeśli to konieczne -->

            </div>
        </div>
        {% else %}
        <div class="card">
            <div class="card-body">
                <a href="{% url 'add_product_to_category' product.id category.id %}"><h6 class="card-title">{{ category.title }}</h6></a>
                <!-- Dodaj tutaj informacje, gdy produkt nie jest związany z tą kategorią -->
            </div>
        </div>
        {% endif %}
    </div>
    {% endfor %}
</div>

        </div>
    </div>
</div>


        </div>
    </div>
</div>
{% endblock %}

templates/adminpanel/login.html
{% extends 'base_admin.html' %}
{% load static %}
{% block content %}
<form action="{% url 'login' %}" method="post">
    {% csrf_token %}
    <label for="email">Email: </label>
    <input id="email" type="email" name="email" maxlength="100" required>
    <label for="password">Password: </label>
    <input id="password" type="password" name="password" maxlength="100" required>
    <input type="submit" value="Submit">
    {{ form.errors }}
</form>


{% endblock %}